services:
  postgres-dev:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: franchise
      POSTGRES_USER: franchiseuser
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  backend-dev:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "9012:8080"
    depends_on:
      - postgres

  frontend-dev:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.production
    ports:
      - "9011:80"

volumes:
  postgres_dev_data:
