services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: franchise
      POSTGRES_USER: franchiseuser
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "9002:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.production
    ports:
      - "9001:80"

volumes:
  postgres_data:
